<a href="https://colab.research.google.com/github/brianb1/2017Challenges/blob/master/Copy_of_Python_For_DataScience_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***<center> Notes for Python for Data Science  (Intro to NumPy and Pandas)</center> ***

In [ ]:
#Importing Packages
import numpy as np
import pandas as pd 


**NumPy Arrays are like Lists but allow for Arthmetic Operations to be performed easily and faster**

In [ ]:
#Suppose we have the 2 lists below representing revenue and cost data for 8 quarters below.
#The first 4 elements represent the 1st year's quarterly data.
#The last 4 elements represent the 2nd year's quarterly data. 
rev_list = [300,350,450,550,320,340,440,580]
cost_list = [250,280,320,360,280,270,340,400]

#Suppose we want to calculate the profit and the following line of code:
#Profit = rev - cost 
#This will throw an error. NumPy arrays on the otherhand allow us to perform arthimetic operations.

#How to create a numpy array => np.array(Insert a list here)
#Note that unlike a list, all numpy array elements have to be of the same datatype. 

#For example:

rev_array = np.array(rev_list)
cost_array = np.array(cost_list)

#Now we can calculate the profit more easily:
profit_array = rev_array - cost_array 
print(profit_array)

#You can perform standard arithmetic operations on numpy arrays such as +,-,*,/ etc.

#You can filter arrays as well. 
#This prints out only the values where the element is greater than 300. 

print(rev_array[rev_array>300])


[ 50  70 130 190  40  70 100 180]
[350 450 550 320 340 440 580]


**<center>Shaping Data Using NumPy</center>**

In [ ]:
#You can view the shape of your array be assessing the .shape property. 
print(rev_array.shape) #Note (8,) indicates 8 rows and 0 columns

#You need to use the reshape method on your array if we you want to structure it. 

print(rev_array.reshape(2,4)) #This results in a 2-d array with 2 rows and 4 columns

#Note that when you use the reshape method, the underlying array is left unchanged.
#One way you can still assess the product of the reshape method is to assign it to a variable.

rev_array_reshaped = rev_array.reshape(2,4,1) #We are reshaping the array to be 3-d here.
print(rev_array_reshaped)

(8,)
[[300 350 450 550]
 [320 340 440 580]]
[[[300]
  [350]
  [450]
  [550]]

 [[320]
  [340]
  [440]
  [580]]]


**<center> Slicing Your Data -AKA Getting What You Want from the Data </center>**


In [ ]:
#The syntax for slicing your data is similar to slicing data from lists. 
#Note that python indexing starts with 0. 

first_quarter_first_year = rev_array[0]

print(first_quarter_first_year)

#Suppose we want to get first three quarters' revenue 

print(rev_array[:3]) #0,1,2 elements gets outputted 

300
[300 350 450]


**<center> Moving onto Pandas- How do you create a DataFrame? </center> **

In [ ]:
#In Pandas, we work with dataframes.

#One way of you can get data is to convert dictionary into a dataframe 

sample_dictionary = [{'a':1,'b':2,'c':3,'d':4},
                    {'a':100,'b':200,'c':300,'d':400}]

df_from_dictionary = pd.DataFrame(sample_dictionary)

print(df_from_dictionary)

     a    b    c    d
0    1    2    3    4
1  100  200  300  400


In [ ]:
#You can also import data from csv, html, xlsx (excel) formats to create a dataframe.

#Suppose you want to read from a csv file. You use Panda's read_csv method. 

df = pd.read_csv("https://raw.githubusercontent.com/gpalrepo/inclass_practice/master/Shark%20Tank%20Companies.csv")

**<center>Some Exploratory Data Analysis</center>**

In [ ]:
print(df.shape) #shape property indicates number of rows and columns in your dataframe.
print(df.info()) # Info method tells you the columns and associated datatypes. 

(495, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 19 columns):
deal                      495 non-null bool
description               495 non-null object
episode                   495 non-null int64
category                  495 non-null object
entrepreneurs             423 non-null object
location                  495 non-null object
website                   457 non-null object
askedFor                  495 non-null int64
exchangeForStake          495 non-null int64
valuation                 495 non-null int64
season                    495 non-null int64
shark1                    495 non-null object
shark2                    495 non-null object
shark3                    495 non-null object
shark4                    495 non-null object
shark5                    495 non-null object
title                     495 non-null object
episode-season            495 non-null object
Multiple Entreprenuers    495 non-null bool
dtypes: bool(2), int

In [ ]:
print(df.head()) #This prints out the first 5 rows in a dataset
print(df.tail()) #This prints out the last 5 rows in a dataset

    deal                                        description  episode  \
0  False             Bluetooth device implant for your ear.        1   
1   True  Retail and wholesale pie factory with two reta...        1   
2   True  Ava the Elephant is a godsend for frazzled par...        1   
3  False  Organizing, packing, and moving services deliv...        1   
4  False  Interactive media centers for healthcare waiti...        1   

              category                entrepreneurs      location  \
0            Novelties               Darrin Johnson  St. Paul, MN   
1       Specialty Food                   Tod Wilson  Somerset, NJ   
2  Baby and Child Care              Tiffany Krumins   Atlanta, GA   
3    Consumer Services  Nick Friedman, Omar Soliman     Tampa, FL   
4    Consumer Services               Kevin Flannery      Cary, NC   

                               website  askedFor  exchangeForStake  valuation  \
0                                  NaN   1000000                15    6

In [ ]:
print(df.columns) #This prints out just the names of the columns 

#You can rename a column's name using the rename method. 
#You need to make sure the key is the orignal name of the column 
#and the value is the new name. 

#Inplace=True ensures that you make the changes to the existing dataframe itself.

df.rename(columns={'website':'company_website'},inplace=True) 

#Let's check to see the column names have been changed.
print(df.columns)

Index(['deal', 'description', 'episode', 'category', 'entrepreneurs',
       'location', 'website', 'askedFor', 'exchangeForStake', 'valuation',
       'season', 'shark1', 'shark2', 'shark3', 'shark4', 'shark5', 'title',
       'episode-season', 'Multiple Entreprenuers'],
      dtype='object')
Index(['deal', 'description', 'episode', 'category', 'entrepreneurs',
       'location', 'company_website', 'askedFor', 'exchangeForStake',
       'valuation', 'season', 'shark1', 'shark2', 'shark3', 'shark4', 'shark5',
       'title', 'episode-season', 'Multiple Entreprenuers'],
      dtype='object')


**<center> Slicing DataFrames Using iloc and loc </center> **

In [ ]:
#How we can access specific rows within our dataframe? 
#iloc method => integer based location indexing

print(df.iloc[0,1]) #Prints out the 1st row and 2nd column. 

print(df.iloc[1:4,5:9]) #Prints out 2nd to 4th row and 6th to 9th row.  

Bluetooth device implant for your ear.
       location                      company_website  askedFor  \
1  Somerset, NJ                  http://whybake.com/    460000   
2   Atlanta, GA       http://www.avatheelephant.com/     50000   
3     Tampa, FL  http://collegehunkshaulingjunk.com/    250000   

   exchangeForStake  
1                10  
2                15  
3                25  


In [ ]:
#iloc isn't intuitive. At times, it better to use label-based filtering.
#The loc method allows us to do that 

#Suppose we want to print the 'valuation' and 'title' columsn of
#all the rows which belong to the Electronics category 

print(df.loc[df['category']=='Electronics',['valuation','title']])

#We can also filter results by boolean values. This outputs all rows in which
#the valuation is greater than 1000000.

print(df.loc[df['valuation']>1000000])


     valuation                title
39    15000000          VirtuSphere
45      200000           Mr. Poncho
46      750000             Ink Flip
94     1000000            Origaudio
110     100000          Tail Lightz
159    1515152  UniKey Technologies
212     207692          SoundBender
231     800000           Cellhelmet
303   20000000         Virtuix Omni
360    2333333                iLumi
379    1000000                Amber
403   30000000             Singtrix
457    2000000             luminAID
477   10000000     Melni Connectors
      deal                                        description  episode  \
0    False             Bluetooth device implant for your ear.        1   
1     True  Retail and wholesale pie factory with two reta...        1   
4    False  Interactive media centers for healthcare waiti...        1   
5     True  One of the first entrepreneurs to pitch on Sha...        2   
8    False  A safety device for seatbelts. It prevents the...        2   
9     True  An e

**<center>Performing Mathematical Operations using Pandas </center> **

In [ ]:
#Sample Mathematical Operations 
#We are performing mathematical operations on the 'valuation' column for the examples.
print(df['valuation'].mean())
print(df['valuation'].median())
print(df['valuation'].std())
print(df['valuation'].max())
print(df['valuation'].min())
print(df['valuation'].count())

#Group By 

#When you apply the groupby function, you are 
#i) Splitting the data into groups based on the criteria you specify
#ii) Applying a function to each group
#iii) Finally, combined the results into one output


#The code below helps us find the median valuation across categories. 

print(df.groupby(['category']).median()['valuation'])



2165614.6767676766
1000000.0
3761971.0078376867
30000000
40000
495
category
Alcoholic Beverages                             6000000.0
Automotive                                      2000000.0
Baby and Child Care                              535714.5
Baby and Children's Apparel and Accessories      700000.0
Baby and Children's Bedding                      412500.0
Baby and Children's Entertainment                833333.0
Baby and Children's Food                        1500000.0
Consumer Services                               1000000.0
Costumes                                         708333.5
Cycling                                         1515152.0
Education                                       2250000.0
Electronics                                     1257576.0
Entertainment                                   1500000.0
Fashion Accessories                             2500000.0
Fitness Apparel and Accessories                  966666.5
Fitness Equipment                               170000

If you have a question, you can post in the #programming-exercises channel on our Discord Server app: https://discord.gg/PqkB5b2.  You can also contact me at gpal@letslearn.tv. 
If you find these classes and notes beneficial, please consider leaving a tip at https://www.buymeacoffee.com/gpal. Thank you for your support! 

